-- 20260729150000_fotmob_comprehensive_schema.sql

-- 1. Expanded Player Stats Columns (guarded: table was created outside migrations in production)
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables
    WHERE table_schema = 'public' AND table_name = 'match_player_stats_fotmob'
  ) THEN
    ALTER TABLE public.match_player_stats_fotmob ADD COLUMN IF NOT EXISTS tackles INT;
    ALTER TABLE public.match_player_stats_fotmob ADD COLUMN IF NOT EXISTS interceptions INT;
    ALTER TABLE public.match_player_stats_fotmob ADD COLUMN IF NOT EXISTS ground_duels_won INT;
    ALTER TABLE public.match_player_stats_fotmob ADD COLUMN IF NOT EXISTS aerials_won INT;
    ALTER TABLE public.match_player_stats_fotmob ADD COLUMN IF NOT EXISTS touches_opp_box INT;
  END IF;
END $$;

-- 2. Teams
CREATE TABLE IF NOT EXISTS public.teams_fotmob (
    fotmob_team_id TEXT PRIMARY KEY,
    name TEXT,
    country TEXT,
    coach_name TEXT,
    updated_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE public.teams_fotmob ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='teams_fotmob' AND policyname='Public read access'
  ) THEN
    CREATE POLICY "Public read access" ON public.teams_fotmob FOR SELECT USING (true);
  END IF;
END $$;

-- 3. Squads
CREATE TABLE IF NOT EXISTS public.team_squad_fotmob (
    fotmob_team_id TEXT REFERENCES public.teams_fotmob(fotmob_team_id),
    fotmob_player_id TEXT,
    player_id BIGINT REFERENCES public.players(id),
    market_value NUMERIC,
    is_coach BOOLEAN DEFAULT false,
    captured_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY(fotmob_team_id, fotmob_player_id)
);
ALTER TABLE public.team_squad_fotmob ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='team_squad_fotmob' AND policyname='Public read access'
  ) THEN
    CREATE POLICY "Public read access" ON public.team_squad_fotmob FOR SELECT USING (true);
  END IF;
END $$;

-- 4. Unavailable Players (Injuries/Suspensions) - historical via date or snapshot
CREATE TABLE IF NOT EXISTS public.team_unavailable_fotmob (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fotmob_team_id TEXT REFERENCES public.teams_fotmob(fotmob_team_id),
    fotmob_player_id TEXT,
    player_id BIGINT REFERENCES public.players(id),
    type TEXT, -- injury, suspension, etc
    expected_return TEXT,
    match_id BIGINT REFERENCES public.matches(id), -- If extracted from matchDetails
    captured_at TIMESTAMPTZ DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_team_unavailable_match ON public.team_unavailable_fotmob(match_id);
ALTER TABLE public.team_unavailable_fotmob ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='team_unavailable_fotmob' AND policyname='Public read access'
  ) THEN
    CREATE POLICY "Public read access" ON public.team_unavailable_fotmob FOR SELECT USING (true);
  END IF;
END $$;

-- 5. Players Profiling
CREATE TABLE IF NOT EXISTS public.players_fotmob (
    fotmob_player_id TEXT PRIMARY KEY,
    player_id BIGINT REFERENCES public.players(id),
    name TEXT,
    birth_date TEXT,
    position_description TEXT,
    height INT,
    preferred_foot TEXT,
    updated_at TIMESTAMPTZ DEFAULT now()
);
ALTER TABLE public.players_fotmob ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='players_fotmob' AND policyname='Public read access'
  ) THEN
    CREATE POLICY "Public read access" ON public.players_fotmob FOR SELECT USING (true);
  END IF;
END $$;

-- 6. Player Market Values (Time-series)
CREATE TABLE IF NOT EXISTS public.player_market_values_fotmob (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fotmob_player_id TEXT REFERENCES public.players_fotmob(fotmob_player_id),
    player_id BIGINT REFERENCES public.players(id),
    date DATE NOT NULL,
    market_value NUMERIC NOT NULL,
    UNIQUE(fotmob_player_id, date)
);
ALTER TABLE public.player_market_values_fotmob ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='player_market_values_fotmob' AND policyname='Public read access'
  ) THEN
    CREATE POLICY "Public read access" ON public.player_market_values_fotmob FOR SELECT USING (true);
  END IF;
END $$;

-- 7. Player Traits (Radar)
CREATE TABLE IF NOT EXISTS public.player_traits_fotmob (
    fotmob_player_id TEXT REFERENCES public.players_fotmob(fotmob_player_id),
    trait_name TEXT,
    value NUMERIC,
    captured_at TIMESTAMPTZ DEFAULT now(),
    PRIMARY KEY(fotmob_player_id, trait_name)
);
ALTER TABLE public.player_traits_fotmob ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE schemaname='public' AND tablename='player_traits_fotmob' AND policyname='Public read access'
  ) THEN
    CREATE POLICY "Public read access" ON public.player_traits_fotmob FOR SELECT USING (true);
  END IF;
END $$;
