-- Preenche nomes de exibição/pt/en/original/apelidos das seleções do FotMob e
-- corrige is_national_team (40 delas estavam false/nulo). Casa SÓ por
-- team_source_ids (source='fotmob'), nunca por nome. A Costa Rica (FotMob 6705)
-- fica de fora de propósito: o time 744 mistura a seleção com um clube
-- brasileiro e precisa de reparo supervisionado antes (ver Achado 43).
-- Chile e Espanha: 'La Roja' só no Chile, para o apelido não ficar ambíguo.
with nomes(fotmob_id, name_en, name_pt, name_native, apelidos) as (values
  (5787, 'Slovenia', 'Eslovênia', 'Slovenija', array[]::text[]),
  (5790, 'Wales', 'País de Gales', 'Cymru', array['Y Dreigiau']::text[]),
  (5791, 'Republic of Ireland', 'Irlanda', 'Éire', array['Boys in Green']::text[]),
  (5796, 'Uruguay', 'Uruguai', 'Uruguay', array['La Celeste']::text[]),
  (5797, 'Bolivia', 'Bolívia', 'Bolivia', array['La Verde']::text[]),
  (5798, 'Peru', 'Peru', 'Perú', array['La Blanquirroja']::text[]),
  (5800, 'Venezuela', 'Venezuela', 'Venezuela', array['La Vinotinto']::text[]),
  (5806, 'Jamaica', 'Jamaica', 'Jamaica', array['Reggae Boyz']::text[]),
  (5810, 'Canada', 'Canadá', 'Canada', array[]::text[]),
  (5857, 'Cuba', 'Cuba', 'Cuba', array[]::text[]),
  (5902, 'Qatar', 'Catar', 'قطر', array['Al-Annabi']::text[]),
  (5922, 'Panama', 'Panamá', 'Panamá', array['Los Canaleros']::text[]),
  (5934, 'Haiti', 'Haiti', 'Haïti', array['Les Grenadiers']::text[]),
  (6262, 'Morocco', 'Marrocos', 'المغرب', array['Leões do Atlas','Atlas Lions']::text[]),
  (6346, 'Nigeria', 'Nigéria', 'Nigeria', array['Super Eagles']::text[]),
  (6383, 'Greece', 'Grécia', 'Ελλάδα', array[]::text[]),
  (6395, 'Senegal', 'Senegal', 'Sénégal', array['Leões de Teranga','Lions of Teranga']::text[]),
  (6595, 'Turkiye', 'Turquia', 'Türkiye', array[]::text[]),
  (6629, 'Cameroon', 'Camarões', 'Cameroun', array['Leões Indomáveis','Lions Indomptables']::text[]),
  (6706, 'Argentina', 'Argentina', 'Argentina', array['La Albiceleste']::text[]),
  (6707, 'Ecuador', 'Equador', 'Ecuador', array['La Tri']::text[]),
  (6708, 'Netherlands', 'Países Baixos', 'Nederland', array['Holanda','Oranje','Laranja Mecânica']::text[]),
  (6710, 'Mexico', 'México', 'México', array['El Tri']::text[]),
  (6711, 'Iran', 'Irã', 'ایران', array['Team Melli']::text[]),
  (6713, 'United States', 'Estados Unidos', 'United States', array['USA','USMNT']::text[]),
  (6714, 'Ghana', 'Gana', 'Ghana', array['Black Stars']::text[]),
  (6715, 'Japan', 'Japão', '日本', array['Samurai Blue']::text[]),
  (6716, 'Australia', 'Austrália', 'Australia', array['Socceroos']::text[]),
  (6717, 'Switzerland', 'Suíça', 'Schweiz', array['Nati']::text[]),
  (6718, 'Ukraine', 'Ucrânia', 'Україна', array[]::text[]),
  (6719, 'Tunisia', 'Tunísia', 'تونس', array['Águias de Cartago','Eagles of Carthage']::text[]),
  (6720, 'Spain', 'Espanha', 'España', array['La Furia Roja']::text[]),
  (6723, 'France', 'França', 'France', array['Les Bleus']::text[]),
  (6724, 'Paraguay', 'Paraguai', 'Paraguay', array['La Albirroja']::text[]),
  (7724, 'Trinidad and Tobago', 'Trinidad e Tobago', 'Trinidad and Tobago', array['Soca Warriors']::text[]),
  (7795, 'Saudi Arabia', 'Arábia Saudita', 'السعودية', array['Green Falcons','Falcões Verdes']::text[]),
  (7804, 'South Korea', 'Coreia do Sul', '대한민국', array['Taegeuk Warriors']::text[]),
  (7871, 'Finland', 'Finlândia', 'Suomi', array['Huuhkajat']::text[]),
  (8204, 'Italy', 'Itália', 'Italia', array['Azzurri','Squadra Azzurra']::text[]),
  (8205, 'Serbia', 'Sérvia', 'Србија', array['Orlovi']::text[]),
  (8238, 'Denmark', 'Dinamarca', 'Danmark', array['Danish Dynamite']::text[]),
  (8255, 'Austria', 'Áustria', 'Österreich', array['Das Team']::text[]),
  (8256, 'Brazil', 'Brasil', 'Brasil', array['Seleção Brasileira','Seleção Canarinho','Canarinho']::text[]),
  (8258, 'Colombia', 'Colômbia', 'Colombia', array['Los Cafeteros']::text[]),
  (8260, 'North Macedonia', 'Macedônia do Norte', 'Северна Македонија', array[]::text[]),
  (8263, 'Belgium', 'Bélgica', 'België', array['Red Devils','Diabos Vermelhos']::text[]),
  (8268, 'Georgia', 'Geórgia', 'საქართველო', array[]::text[]),
  (8361, 'Portugal', 'Portugal', 'Portugal', array['Seleção das Quinas']::text[]),
  (8491, 'England', 'Inglaterra', 'England', array['Three Lions']::text[]),
  (8496, 'Czechia', 'Tchéquia', 'Česko', array['República Tcheca','Czech Republic']::text[]),
  (8497, 'Slovakia', 'Eslováquia', 'Slovensko', array[]::text[]),
  (8498, 'Scotland', 'Escócia', 'Alba', array['Tartan Army']::text[]),
  (8520, 'Sweden', 'Suécia', 'Sverige', array['Blågult']::text[]),
  (8536, 'Iceland', 'Islândia', 'Ísland', array[]::text[]),
  (8565, 'Hungary', 'Hungria', 'Magyarország', array['Magiares']::text[]),
  (8568, 'Poland', 'Polônia', 'Polska', array[]::text[]),
  (8570, 'Germany', 'Alemanha', 'Deutschland', array['Die Mannschaft']::text[]),
  (8713, 'Russia', 'Rússia', 'Россия', array[]::text[]),
  (9730, 'Romania', 'Romênia', 'România', array[]::text[]),
  (9762, 'Chile', 'Chile', 'Chile', array['La Roja']::text[]),
  (10024, 'Albania', 'Albânia', 'Shqipëria', array[]::text[]),
  (10155, 'Croatia', 'Croácia', 'Hrvatska', array['Vatreni']::text[]),
  (10255, 'Egypt', 'Egito', 'مصر', array['Os Faraós','Pharaohs']::text[]),
  (10259, 'Northern Ireland', 'Irlanda do Norte', 'Northern Ireland', array['Green and White Army']::text[])
)
update public.teams t set
  is_national_team = true,
  display_name = coalesce(t.display_name, n.name_pt),
  name_pt = n.name_pt,
  name_en = n.name_en,
  name_native = n.name_native,
  nicknames = n.apelidos
from nomes n
join public.team_source_ids s on s.source = 'fotmob' and s.source_id = n.fotmob_id::text
where t.id = s.team_id;
